### ISSUE TITLE
Is it possible to use TNeo with low-power modes? 

### ISSUE THREAD

**Issue by Mozilla9** [dimonomid/tneo#1]
Hi. I have some questions.

I would use a low-power mode. I didn't find any information in docs about that.

1) Is it a possible with TNeo?
2) Where is the best place to move MCU a sleep mode?

**Comment by dimonomid** [comment]
Hi,

the right place to put MCU to sleep is the idle task callback: `cb_idle` passed to [`tn_sys_start()`](https://dfrank.bitbucket.io/tneokernel_api/dev/html/tn__sys_8h.html#a62ab25d9d8ca01c02d368968f19e49bf).

Thanks for the question btw: I realized that docs are unclear about it. Not only unclear, but confusing: docs for [TN_CBIdle](https://dfrank.bitbucket.io/tneokernel_api/dev/html/tn__sys_8h.html#ac53892c962d429fadf7cf508024eec66) say that it's illegal to sleep in this function. What is meant is that task sleep is illegal (e.g. `tn_task_sleep()` or any other service which could wait), but MCU sleep is, of course, legal.

The only place I wrote about idle task callback is in the article: https://dmitryfrank.com/articles/how_i_ended_up_writing_my_own_kernel#idle_task . I'll clarify that in docs as well.

**Comment by Mozilla9** [comment]
Thanks. I will try it.
