### ISSUE TITLE
Error during build with GCC-7.2

### ISSUE THREAD

**Issue by 110yd** [dimonomid/tneo#10]
Architecture: ARM Cortex M4F
Compiler: Linaro gcc-arm-none-eabi-7-2017-q4-major (bundled with TI Code Composer Studio v8.0.0)

During the build this warning is treated as error, so the build fails:

`src/arch/cortex_m/tn_arch_cortex_m.S:303:22: error: this use of "defined" may not be portable [-Werror=expansion-to-defined]
 #if _TN_NEED_SAVE_LR()
                      ^
src/arch/cortex_m/tn_arch_cortex_m.S:400:22: error: this use of "defined" may not be portable [-Werror=expansion-to-defined]
 #if _TN_NEED_SAVE_LR()
                      ^
src/arch/cortex_m/tn_arch_cortex_m.S:489:22: error: this use of "defined" may not be portable [-Werror=expansion-to-defined]
 #if _TN_NEED_SAVE_LR()
                      ^
cc1: all warnings being treated as errors
make[1]: *** [_obj/cortex_m4f/arm-none-eabi-gcc/tn_arch_cortex_m.o] Ошибка 1
make: *** [all] Ошибка 2
`

**Comment by embeddedt** [comment]
This is just warning you of a potential portability issue, not an actual error.

Since you are using GCC, and it should be able to handle this, you can disable it with `-Wno-error=expansion-to-defined`, and it should work just fine.

**Comment by dimonomid** [comment]
Sorry for the late response, but yeah it's a non-issue, so closing it.
