### ISSUE TITLE
Unit-tests repository not available

### ISSUE THREAD

**Issue by arhiv6** [dimonomid/tneo#14]
Error accessing repository with tests.

https://github.com/dimonomid/tneo/blob/8f95d2084060c45067f0ce5631a11b83a3463cdf/stuff/doc_pages/unit_tests.dox#L161

Error: HTTP Error 503: Service Unavailable

**Comment by arhiv6** [comment]
In old repo (on bitbucket) available project [tntest](https://bitbucket.org/dfrank/tntest). It is actual code?

**Comment by dimonomid** [comment]
Sorry for the late response.

Yes your link is the actual repo with tests. The most relevant test code is located in this dir https://bitbucket.org/dfrank/tntest/src/master/project_common/tntest_common/src/c/policy/appl_tntest/
