### ISSUE TITLE
Links to documentation is broken

### ISSUE THREAD

**Issue by happysalada** [dimonomid/tneo#15]
It looks like a great project!

In the readme, all the links to the documentation return a 404.
They all link to some special bitbucket repo, that doesn't seem to exist.
I'm curious about reading the documentation.

**Comment by dimonomid** [comment]
This was actually addressed 2+ years ago ( https://github.com/dimonomid/tneo/commit/6c94ccc4f2ffb84d86afd2d41e868a77164c9c40 ), but I forgot to close the issue. Closing now.
