### ISSUE TITLE
Please add a license file.

### ISSUE THREAD

**Issue by Michael-S** [dimonomid/tneo#2]
Hello dimonomid,

I see that the original TNKernel and the andersm/TNKernel-PIC32 are under the BSD license.  Could you please add a LICENSE or COPYING file or section in the README with the license you choose?  

Thanks.

**Comment by dimonomid** [comment]
Yeah, license text is included in every source file, e.g. [tn.h](https://github.com/dimonomid/tneo/blob/master/src/tn.h), but you're right that I should also create a LICENSE file. Thanks for pointing this out, I'll do that soon.

**Comment by Michael-S** [comment]
Ah, I wouldn't have said anything if I had seen it on the actual .c or .h files.  I feel foolish for not looking.  Sorry for wasting some of your time.
