### ISSUE TITLE
The docs are not available by provided links.

### ISSUE THREAD

**Issue by Mozilla9** [dimonomid/tneo#4]
Hi, Dmitry.

The links on docs haven't worked. It opens the bitbucket.org main face instead.

**Comment by dimonomid** [comment]
Thanks for reporting that! Apparently [Attlassian announced the move from bitbucket.org to bitbucket.io](https://confluence.atlassian.com/bitbucket/publishing-a-website-on-bitbucket-cloud-221449776.html) some time ago, but they weren't loud enough for me to notice that, so I ended up having broken links.

Fixed now.
