### ISSUE TITLE
I got many warnings when that was compiled with GCC 'Pedantic'-mode

### ISSUE THREAD

**Issue by Mozilla9** [dimonomid/tneo#5]
Hi.

1) When I'm using the 'Pedantic' mode I got warnings like this:

```
../wm-core/src/tneo/src/core/internal/_tn_timer.h: In function '_tn_timer_callback_call':
../wm-core/src/tneo/src/core/internal/_tn_timer.h:182:20: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
    TN_INT_IRESTORE();

../wm-core/src/tneo/src/core/tn_tasks.c: In function '_task_terminate':
../wm-core/src/tneo/src/core/tn_tasks.c:356:25: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
       _TN_FATAL_ERROR("");

```

2) I have seen strange macros in file `tn_arch_cortex_m.h`. This file is part of `arm-cortex` arch and `PIC32` prefix surprised me.

```
#define TN_INT_RESTORE()    _TN_PIC32_INTSAVE_CHECK();                      \
                            tn_arch_sr_restore(TN_INTSAVE_VAR)
```

**Comment by dimonomid** [comment]
Hi, thanks.

(1) I guess I never tried to build it in pedantic mode, so yeah, I will.

(2) is a copy pasta problem: the macro `_tn_PIC32_INTSAVE_CHECK` is defined in the same file `tn_arch_cortex_m.h`, surely the name is wrong, I'll fix it.

**Comment by dimonomid** [comment]
The (2) part is fixed, it's easy.

(1) is not so easy. I resolved it for Cortex-M architectures (and added `-pedantic` to the Makefile), but for PICs I'm afraid I won't fix it: there are top-class "BFA" (Bit Field Access) macros, like [this one](https://github.com/dimonomid/tneo/blob/master/src/arch/pic32/tn_arch_pic32_bfa.h#L154), and they are only made possible by the ["statement expression"](https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html) feature of GCC. Of course, in pedantic mode it complains that this is non-standard, and I'm not going to ditch those macros.
