### ISSUE TITLE
Sources were not compiling in case TN_DEBUG=1 and TN_USE_MUTEXES=0

### ISSUE THREAD

**Issue by Mozilla9** [dimonomid/tneo#6]
I got this error:

```
../tn_tasks.c: In function '_tn_task_set_dormant':
../tn_tasks.c:1117:39: error: 'struct TN_Task' has no member named 'mutex_queue'
    } else if (!_tn_list_is_empty(&task->mutex_queue)){

```

**Comment by dimonomid** [comment]
Thanks for reporting! Fixed.

TODO: add tests which would ensure that the kernel can be built with all possible combination of build options. Of course, ideally I should also run the unit-tests in the hardware for each build, but so far I'm not very optimistic about my time to implement it.
